# Generated by Django 4.2.21 on 2025-10-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0003_alter_resource_target_audience"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="学习路径描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_path",
                        to="categories.technologycategory",
                        verbose_name="关联技术分类",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="阶段标题")),
                ("description", models.TextField(blank=True, verbose_name="阶段描述")),
                ("order", models.PositiveIntegerField(verbose_name="阶段顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="learning_paths.learningpath",
                        verbose_name="所属学习路径",
                    ),
                ),
                (
                    "recommended_resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_stages",
                        to="resources.resource",
                        verbose_name="推荐学习资源",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
    ]
