# Generated by Django 4.2.21 on 2025-10-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0001_initial"),
    ]

    operations = []
