# Generated by Django 4.2.21 on 2025-10-15 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
        ("learning_paths", "0004_fix_field_mapping"),
    ]

    operations = [
        migrations.RemoveField(model_name="learningpath", name="category",),
        migrations.AddField(
            model_name="learningpath",
            name="technology",
            field=models.OneToOneField(
                blank=True,
                db_column="technology_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_path",
                to="categories.technologycategory",
                verbose_name="关联技术分类",
            ),
        ),
        migrations.CreateModel(
            name="UserLearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="learning_paths.learningstage",
                        verbose_name="学习阶段",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户学习进度",
                "verbose_name_plural": "用户学习进度",
                "unique_together": {("user", "stage")},
            },
        ),
    ]
