# Generated by Django 4.2.21 on 2025-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_remove_resource_approved_by_and_more"),
        (
            "learning_paths",
            "0005_remove_learningpath_category_learningpath_technology_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningstage",
            name="recommended_resources",
            field=models.ManyToManyField(
                blank=True,
                db_table="learning_paths_learningstage_resources",
                related_name="learning_stages",
                to="resources.resource",
                verbose_name="推荐学习资源",
            ),
        ),
    ]
