# Generated by Django 4.2.21 on 2025-06-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资源名称")),
                ("description", models.TextField(blank=True, verbose_name="资源描述")),
                ("url", models.URLField(verbose_name="资源链接")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("book", "书籍"),
                            ("video", "视频"),
                            ("article", "文章"),
                            ("course", "课程"),
                        ],
                        default="book",
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=0, verbose_name="评分（1-5）"),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="适用人群（如：零基础/进阶）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="related_resources",
                        to="categories.technologycategory",
                        verbose_name="关联技术分类",
                    ),
                ),
            ],
        ),
    ]
