# Generated by Django 4.2.21 on 2025-10-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="target_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "零基础"),
                    ("junior", "初级开发者"),
                    ("intermediate", "中级开发者"),
                    ("advanced", "高级开发者"),
                ],
                max_length=20,
                null=True,
                verbose_name="适用人群",
            ),
        ),
    ]
