# Generated by Django 4.2.21 on 2025-10-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_resource_target_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="target_audience",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="适用人群（如：零基础/进阶）"
            ),
        ),
    ]
