# Generated by Django 4.2.21 on 2025-10-25 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0003_alter_resource_target_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="reject_reason",
            field=models.TextField(blank=True, verbose_name="拒绝原因"),
        ),
        migrations.AddField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交用户",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True, default=3, null=True, verbose_name="评分（1-5）"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("book", "书籍"),
                    ("video", "视频"),
                    ("article", "文章"),
                    ("course", "课程"),
                    ("project", "项目"),
                    ("tool", "工具"),
                    ("document", "文档"),
                ],
                default="article",
                max_length=20,
                verbose_name="资源类型",
            ),
        ),
    ]
