# Generated by Django 4.2.21 on 2025-10-25 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "learning_paths",
            "0005_remove_learningpath_category_learningpath_technology_and_more",
        ),
        ("resources", "0004_resource_reject_reason_resource_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核用户",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="target_learning_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_resources",
                to="learning_paths.learningpath",
                verbose_name="目标学习路径",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="rating",
            field=models.PositiveIntegerField(default=0, verbose_name="评分（1-5）"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("book", "书籍"),
                    ("video", "视频"),
                    ("article", "文章"),
                    ("course", "课程"),
                ],
                default="book",
                max_length=20,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交用户",
            ),
        ),
    ]
