# Generated by Django 4.2.21 on 2025-10-25 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "resources",
            "0005_resource_approved_by_resource_target_learning_path_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="resource", name="reject_reason",),
        migrations.RemoveField(model_name="resource", name="target_learning_path",),
        migrations.AlterField(
            model_name="resource",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核管理员",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("book", "书籍"),
                    ("video", "视频"),
                    ("article", "文章"),
                    ("course", "课程"),
                    ("project", "项目"),
                    ("tool", "工具"),
                    ("document", "文档"),
                ],
                default="book",
                max_length=20,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="投稿用户",
            ),
        ),
    ]
