# Generated by Django 4.2.21 on 2025-10-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0006_remove_resource_reject_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="resource", name="approved_by",),
        migrations.RemoveField(model_name="resource", name="updated_at",),
        migrations.AddField(
            model_name="resource",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="resource",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="approved",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="投稿人",
            ),
        ),
    ]
