# Generated by Django 4.2.21 on 2025-11-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_remove_resource_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="content_source",
            field=models.CharField(
                choices=[
                    ("original", "站内原创/上传"),
                    ("embedded", "第三方嵌入"),
                    ("linkout", "外部跳转"),
                ],
                default="original",
                max_length=20,
                verbose_name="内容来源",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="document_source_url",
            field=models.URLField(blank=True, verbose_name="文档来源链接"),
        ),
        migrations.AddField(
            model_name="resource",
            name="hero_cover",
            field=models.URLField(blank=True, verbose_name="封面图"),
        ),
        migrations.CreateModel(
            name="ResourceContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "body_markdown",
                    models.TextField(blank=True, verbose_name="正文 Markdown"),
                ),
                ("body_html", models.TextField(blank=True, verbose_name="正文 HTML")),
                (
                    "body_format",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("plaintext", "纯文本"),
                        ],
                        default="markdown",
                        max_length=20,
                        verbose_name="正文格式",
                    ),
                ),
                (
                    "sections",
                    models.JSONField(blank=True, default=list, verbose_name="章节/目录结构"),
                ),
                (
                    "embed_provider",
                    models.CharField(blank=True, max_length=50, verbose_name="嵌入提供方"),
                ),
                ("embed_url", models.URLField(blank=True, verbose_name="嵌入地址")),
                (
                    "embed_meta",
                    models.JSONField(blank=True, default=dict, verbose_name="嵌入元信息"),
                ),
                ("document_html", models.TextField(blank=True, verbose_name="文档 HTML")),
                (
                    "document_toc",
                    models.JSONField(blank=True, default=list, verbose_name="文档目录"),
                ),
                ("download_url", models.URLField(blank=True, verbose_name="下载链接")),
                (
                    "extra_links",
                    models.JSONField(blank=True, default=list, verbose_name="附加链接"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="resources.resource",
                        verbose_name="资源",
                    ),
                ),
            ],
            options={"verbose_name": "资源内容", "verbose_name_plural": "资源内容",},
        ),
    ]
