# Generated by Django 4.2.21 on 2025-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resources",
            "0008_resource_content_source_resource_document_source_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecontent",
            name="document_selector",
            field=models.CharField(
                blank=True,
                help_text="CSS选择器，用于提取第三方文档的特定部分，如: #content, .main-content, article",
                max_length=200,
                verbose_name="文档内容选择器",
            ),
        ),
    ]
