# Generated by Django 4.2.21 on 2025-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_resourcecontent_document_selector"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecontent",
            name="document_remove_selectors",
            field=models.CharField(
                blank=True,
                help_text="从提取的内容中移除不需要的元素，如：.sidebar, .ads, footer",
                max_length=500,
                verbose_name="需要移除的元素选择器（逗号分隔）",
            ),
        ),
        migrations.AlterField(
            model_name="resourcecontent",
            name="document_selector",
            field=models.CharField(
                blank=True,
                help_text="用于从第三方页面提取特定部分，如：main, .content, #article-body",
                max_length=200,
                verbose_name="文档内容选择器（CSS选择器）",
            ),
        ),
    ]
