# Generated by Django 4.2.21 on 2025-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0010_resourcecontent_document_remove_selectors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcecontent", name="document_remove_selectors",
        ),
        migrations.AddField(
            model_name="resourcecontent",
            name="document_base_url",
            field=models.URLField(blank=True, verbose_name="文档基础URL（用于转换相对链接）"),
        ),
        migrations.AlterField(
            model_name="resourcecontent",
            name="document_selector",
            field=models.CharField(
                blank=True,
                help_text="例如: .main-content, #article-body, article",
                max_length=200,
                verbose_name="内容选择器（CSS选择器）",
            ),
        ),
    ]
