# Generated by Django 4.2.21 on 2025-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_remove_resourcecontent_document_remove_selectors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecontent",
            name="document_pages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="存储多个页面的信息，格式：[{url, title, html, toc, order}]",
                verbose_name="文档页面列表",
            ),
        ),
    ]
