# Generated by Django 4.2.21 on 2025-11-21 16:04

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0012_resourcecontent_document_pages"),
    ]

    operations = [
        migrations.RemoveField(model_name="resourcecontent", name="document_base_url",),
        migrations.RemoveField(model_name="resourcecontent", name="document_pages",),
        migrations.RemoveField(model_name="resourcecontent", name="document_selector",),
        migrations.AlterField(
            model_name="resourcecontent",
            name="document_toc",
            field=models.JSONField(
                blank=True, default=resources.models.default_list, verbose_name="文档目录"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecontent",
            name="embed_meta",
            field=models.JSONField(
                blank=True, default=resources.models.default_dict, verbose_name="嵌入元信息"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecontent",
            name="extra_data",
            field=models.JSONField(
                blank=True, default=resources.models.default_dict, verbose_name="扩展数据"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecontent",
            name="extra_links",
            field=models.JSONField(
                blank=True, default=resources.models.default_list, verbose_name="附加链接"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecontent",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=resources.models.default_list,
                verbose_name="章节/目录结构",
            ),
        ),
    ]
