# Generated by Django 4.2.21 on 2025-11-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0013_remove_resourcecontent_document_base_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="resource", name="document_source_url",),
    ]
