# Generated by Django 4.2.21 on 2025-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0015_convert_video_to_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("book", "书籍"),
                    ("course", "课程"),
                    ("article", "文章"),
                    ("project", "项目"),
                    ("tool", "工具"),
                    ("document", "文档"),
                ],
                default="book",
                max_length=20,
                verbose_name="资源类型",
            ),
        ),
    ]
