# Generated by Django 4.2.21 on 2025-11-21 17:10

from django.db import migrations


def migrate_video_to_course(apps, schema_editor):
    """将现有的 video 类型资源改为 course 类型"""
    Resource = apps.get_model('resources', 'Resource')
    Resource.objects.filter(resource_type='video').update(resource_type='course')


def reverse_migrate(apps, schema_editor):
    """回滚：将 course 类型改回 video（仅用于回滚）"""
    Resource = apps.get_model('resources', 'Resource')
    # 注意：这个回滚可能会将原本就是 course 的资源也改为 video
    # 如果需要精确回滚，需要额外的标记字段
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0016_alter_resource_resource_type"),
    ]

    operations = [
        migrations.RunPython(migrate_video_to_course, reverse_migrate),
    ]

