# Generated by Django 4.2.21 on 2025-11-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0017_migrate_video_to_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="resourcecontent", name="summary",),
    ]
