# Generated by Django 4.2.21 on 2025-11-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0018_remove_summary_field"),
    ]

    operations = []
