# Generated by Django 4.2.21 on 2025-11-23 09:05

from django.db import migrations


def fix_charset(apps, schema_editor):
    """
    修复 body_html 和 document_html 字段的字符集为 utf8mb4
    以支持 emoji 等 4 字节 UTF-8 字符
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 修改 resources_resourcecontent 表的字符集
        # 确保 body_html 和 document_html 字段使用 utf8mb4
        try:
            cursor.execute("""
                ALTER TABLE resources_resourcecontent 
                MODIFY COLUMN body_html TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            """)
        except Exception as e:
            print(f"修改 body_html 字符集时出错: {e}")
        
        try:
            cursor.execute("""
                ALTER TABLE resources_resourcecontent 
                MODIFY COLUMN document_html TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            """)
        except Exception as e:
            print(f"修改 document_html 字符集时出错: {e}")
        
        try:
            cursor.execute("""
                ALTER TABLE resources_resourcecontent 
                MODIFY COLUMN body_markdown TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            """)
        except Exception as e:
            print(f"修改 body_markdown 字符集时出错: {e}")


def reverse_fix_charset(apps, schema_editor):
    """
    回滚操作（如果需要）
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 回滚到 utf8（不推荐，但保留回滚能力）
        try:
            cursor.execute("""
                ALTER TABLE resources_resourcecontent 
                MODIFY COLUMN body_html TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;
            """)
            cursor.execute("""
                ALTER TABLE resources_resourcecontent 
                MODIFY COLUMN document_html TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;
            """)
            cursor.execute("""
                ALTER TABLE resources_resourcecontent 
                MODIFY COLUMN body_markdown TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;
            """)
        except Exception as e:
            print(f"回滚字符集时出错: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0019_fix_document_html_charset"),
    ]

    operations = [
        migrations.RunPython(fix_charset, reverse_fix_charset),
    ]
