# Generated by Django 4.2.21 on 2025-11-23 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0020_fix_body_html_charset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资源标题")),
                ("description", models.TextField(blank=True, verbose_name="资源描述")),
                ("url", models.URLField(verbose_name="资源链接")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("book", "书籍"),
                            ("course", "课程"),
                            ("article", "文章"),
                            ("project", "项目"),
                            ("tool", "工具"),
                            ("document", "文档"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(blank=True, max_length=100, verbose_name="适用人群"),
                ),
                (
                    "reason",
                    models.TextField(help_text="说明为什么无法使用自动抓取功能", verbose_name="申请理由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                ("admin_notes", models.TextField(blank=True, verbose_name="管理员备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_request",
                        to="resources.resource",
                        verbose_name="创建的资源",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源添加申请",
                "verbose_name_plural": "资源添加申请",
                "ordering": ["-created_at"],
            },
        ),
    ]
