# Generated by Django 4.2.21 on 2025-11-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0021_resourcerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="管理员审核时的反馈意见", verbose_name="管理员反馈"
            ),
        ),
    ]
