# Generated by Django 4.2.21 on 2025-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0022_resource_admin_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="content_source",
            field=models.CharField(
                choices=[("original", "站内原创/上传"), ("embedded", "外部导入")],
                default="original",
                max_length=20,
                verbose_name="内容来源",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(blank=True, verbose_name="资源链接"),
        ),
    ]
