# Generated by Django 4.2.21 on 2025-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0023_make_url_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecontent",
            name="book_file",
            field=models.FileField(
                blank=True,
                help_text="支持PDF、EPUB、MOBI等格式",
                null=True,
                upload_to="books/%Y/%m/%d/",
                verbose_name="书籍文件",
            ),
        ),
    ]
