# Generated by Django 4.2.21 on 2025-12-06 07:11

from django.db import migrations, models


def migrate_target_audience_data(apps, schema_editor):
    """将现有的 target_audience 值映射到新的 choices 值"""
    Resource = apps.get_model('resources', 'Resource')
    
    # 映射规则：旧值 -> 新值
    mapping = {
        '零基础': 'beginner',
        '入门': 'beginner',
        '入门阶段': 'beginner',
        '初级': 'beginner',
        'elementary': 'beginner',
        '中级': 'intermediate',
        '进阶': 'intermediate',
        '中级阶段': 'intermediate',
        '高级': 'advanced',
        '高级阶段': 'advanced',
    }
    
    # 更新所有资源
    for resource in Resource.objects.all():
        if resource.target_audience:
            old_value = resource.target_audience.strip()
            # 如果旧值在映射表中，使用映射值；否则设为空
            new_value = mapping.get(old_value, '')
            resource.target_audience = new_value
            resource.save(update_fields=['target_audience'])


def reverse_migrate_target_audience_data(apps, schema_editor):
    """反向迁移：将 choices 值映射回显示值"""
    Resource = apps.get_model('resources', 'Resource')
    
    # 反向映射：新值 -> 显示值
    reverse_mapping = {
        'beginner': '入门阶段',
        'intermediate': '中级阶段',
        'advanced': '高级阶段',
    }
    
    # 更新所有资源
    for resource in Resource.objects.all():
        if resource.target_audience:
            old_value = resource.target_audience
            # 将 choices 值映射回显示值
            new_value = reverse_mapping.get(old_value, old_value)
            resource.target_audience = new_value
            resource.save(update_fields=['target_audience'])


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0024_add_book_file_field"),
    ]

    operations = [
        # 先修改字段结构（允许所有值通过）
        migrations.AlterField(
            model_name="resource",
            name="target_audience",
            field=models.CharField(
                blank=True,
                max_length=100,  # 临时保持原长度，方便数据迁移
                verbose_name="适用人群",
            ),
        ),
        # 执行数据迁移
        migrations.RunPython(migrate_target_audience_data, reverse_migrate_target_audience_data),
        # 再修改为最终的 choices 字段
        migrations.AlterField(
            model_name="resource",
            name="target_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "入门阶段"),
                    ("intermediate", "中级阶段"),
                    ("advanced", "高级阶段"),
                ],
                max_length=20,
                verbose_name="适用人群",
            ),
        ),
    ]
