# Generated by Django 4.2.21 on 2025-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="technologycategory", name="icon",),
        migrations.RemoveField(model_name="technologycategory", name="icon_color",),
        migrations.AddField(
            model_name="technologycategory",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                help_text="分类图标图片，建议尺寸：64x64px 或 128x128px，支持 PNG、SVG 格式",
                null=True,
                upload_to="category_icons/",
            ),
        ),
    ]
