# Generated by Django 4.2.21 on 2025-10-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="categories",),
    ]
