# Generated by Django 4.2.21 on 2025-11-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_remove_question_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("question", "帖子"), ("answer", "评论")],
                        max_length=20,
                        verbose_name="对象类型",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="举报原因")),
                ("description", models.TextField(blank=True, verbose_name="补充说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("resolved", "已处理"),
                            ("dismissed", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="举报时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                ("resolution_notes", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.answer",
                        verbose_name="被举报评论",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.question",
                        verbose_name="被举报帖子",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区举报",
                "verbose_name_plural": "社区举报",
                "ordering": ["-created_at"],
            },
        ),
    ]
