# Generated by Django 4.2.21 on 2025-11-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_communityreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityreport",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="community.answer",
                verbose_name="被举报评论",
            ),
        ),
        migrations.AlterField(
            model_name="communityreport",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="community.question",
                verbose_name="被举报帖子",
            ),
        ),
    ]
