# Generated by Django 4.2.21 on 2025-12-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_remove_questionlike"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="is_anonymous",),
        migrations.RemoveField(model_name="question", name="is_anonymous",),
    ]
