# Generated by Django 4.2.21 on 2025-12-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_remove_anonymous_fields"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="updated_at",),
    ]
